version: '3'
services:
    apps_wp:
        build: ./php7.4-apache
        container_name: apps_wp
        volumes:
            - ./apps:/var/www/html
            - ./logs/apache2:/var/log/apache2
        env_file:
            - .env
        ports:
            - 81:80
    server_wp:
        build: ./server
        container_name: server_wp
        tty: true
        stdin_open: true
        ports:
            - 80:80
    database_wp:
        image: mysql:8
        container_name: database_wp
        command: --collation-server=utf8mb4_unicode_ci
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - 3306:3306
